### Test 1: Valid POST Request
POST http://127.0.0.1:5001/api/jobs/recommend
Content-Type: application/json

{
  "job_title": "Operations Manager",
  "skills": ["leadership", "data analysis", "supply chain"],
  "location": "Tulsa, OK"
}

### Test 2: Missing Field
POST http://127.0.0.1:5001/api/jobs/recommend
Content-Type: application/json

{
  "job_title": "Operations Manager",
  "skills": ["leadership", "data analysis"]
}

### Test 3: Adzuna Job Search
POST http://127.0.0.1:5001/api/jobs/search
Content-Type: application/json

{
  "query": "data analyst",
  "location": "New York",
  "resultsPerPage": 5,
  "salaryMin": 60000,
  "salaryMax": 130000
}

### Test 4 Get User Profile
GET http://localhost:5001/api/users/me
X-User-Id: 1

### Test 5: Update User Profile
PUT http://localhost:5001/api/users/me/profile
Content-Type: application/json
X-User-Id: 1

{
  "full_name": "Napoleon Foatobang",
  "email": "napoleon@example.com",
  "location": "Tulsa, OK",
  "phone": "+1-918-555-1290",
  "job_preferences": {
    "locations": ["Tulsa", "Remote"],
    "type": "Full-time"
  },
  "desired_salary": 1234
}

### Test 6: Save Job (job_id must exist from Test 3 response)
POST http://127.0.0.1:5001/api/users/me/saved-jobs
Content-Type: application/json
X-User-Id: 1

{
  "job_id": 1,
  "notes": "This one looks interesting"
}

### Test 7: Get Saved Jobs
GET http://127.0.0.1:5001/api/users/me/saved-jobs
X-User-Id: 1

### Test 8: Remove Saved Job
DELETE http://127.0.0.1:5001/api/users/me/saved-jobs/1
X-User-Id: 1

### Test 9: Apply for a job (job should exist from Test 3 response)
POST http://127.0.0.1:5001/api/users/me/applied-jobs
Content-Type: application/json
X-User-Id: 1

{
  "job_id": 22
}
